jwt:
  secret: SECRET_KEY
logging:
  level:
    root: info
    pl.urz: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug

spring:
  application:
    name: ssur_app
  datasource:
    url: 'jdbc:mysql://localhost:3306/ssur_mysql'
    username: root
    password: qwerty123
    driver-class-name: com.mysql.cj.jdbc.Driver
  autoconfigure:
    exclude:
      org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ssur.application@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    password: gcqncvdxglmyrjvv
mybatis:
  mapperLocations: /mappers/*.xml
